---
- name: 호스트의 사용자 목록을 얻는다
  hosts: all
  tasks:
    - name: /etc/passwd에서 사용자 이름 추출
      command: cut --delimiter=':' --fields=1 /etc/passwd
      register: usernames_result
    - name: 명령을 실행한 결과에서 존재하는 사용자 이름을 목록으로 생성
      # palybook에서 새로운 변수를 반들기 위해서는 set_fact 모듈 사용
      set_fact:
        username_list: "{{ usernames_result.stdout_lines }}"
    # with_items
    # * 지시문에 반복할 목록을 전달하는 것만으로 각 요소에서 item이라는 변수로 데이터에 접근 가능
    - name: 모든 사용자가 있는지 확인
      user:
        name: "{{ item }}"
        createhome: false # user 모듈의 기본동작에 홈 디렉토리가 없으면 새롭게 생성하게 되어 있어서 false로 지정
      with_items: "{{ username_list }}"
