---
- name: libselinux-python과 EPEL 리포지터리 설치
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - epel-release

- name: 엔진엑스 설치
  yum:
    name: nginx
    state: present

- name: 엔진엑스 시작과 자동 시작 설정
  service:
    name: nginx
    state: started
    enabled: true

# template 모듈을 사용하여 템플릿을 활용하는 태스크
- name: nginx.conf 템플릿 활용
  template:
    # templates 디렉토리에 있는 파일이라면 디렉토리 경로를 지정하지 않아도 templates 모듈의 src 옵션 지정 가능
    src: nginx.j2.conf
    dest: /etc/nginx/nginx.conf
    # validate에서 지정된 검증 명령이 실패하면 유요하지 않은 값이 파일에 있는 것으로 판정되어 dest에 지정한 경로에 파일이 복사되기 전에 태스크 실패
    # %s에는 플레이북이 실행될 때 앤서블이 자동으로 생성하는 임시 파일의 경로 설정된다. validate에서 지정한 명령어가 실행되는 것은 실제 설치 경로(dest)에 파일이 적용되기 전이다.
    validate: nginx -t -c %s
  notify:
    - 엔진엑스 리로드

- name: 엔진엑스용 그룹 작성
  group:
    name: "{{ nginx_group }}"
    system: true

- name: 엔진엑스용 사용자 작성
  # user 모듈의 인수
  # * home: 사용자의 홈 경로
  # * shell: 사용자의 로그인용 셸(/sbin/nologin 은 로그인 하지 않은 사용자의 설정)
  # * groups: 사용자가 할당될 그룹, 여러 개 지정할 때는 콤마(,) 사용
  # * append: false(기본값)면 사용자가 할당될 그룹을 groups에 설정된 값으로 변경함. true면 변경하지 않고 그룹에 추가.
  user:
    name: "{{ nginx_user }}"
    home: /var/lib/nginx
    shell: /sbin/nologin
    groups: "{{ nginx_group }}"
    append: true
    system: true
